<a href="https://colab.research.google.com/github/ngyzy/My_First_Repo/blob/main/MC_Data_Analytics_MCLASS7_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MODULE 7.2**



---



**Tutor: Mr Costley**



---

**Topic: Test Classification**



**SUB TOPIC: INTRODUCTION TO MACHINE LEARNING**

**UNSUPERVISED MACHINE LEARNING & DIMENSIONAL REDUCTION**

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [12]:
#import csv file
df=pd.read_csv("/content/DATA/spam.csv",encoding='latin1')


In [13]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [14]:
#rename
df=df.rename(columns={'v1':'label','v2':'message'})

In [15]:
df=df[['label','message']]

In [ ]:
df

In [17]:
print(df['label'].value_counts())

label
ham     4825
spam     747
Name: count, dtype: int64


In [ ]:
#Data cleaning is data manipulation while data preprocessing is getting the data ready to train the model

In [19]:
#preprocess text
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score,classification_report

In [20]:
#split data into categories (features (represented by X) and target represented by Y)
X=df['message']
y=df['label']

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [24]:
X_train.head()

1978    No I'm in the same boat. Still here at my moms...
3989    (Bank of Granite issues Strong-Buy) EXPLOSIVE ...
3935       They r giving a second chance to rahul dengra.
4078       O i played smash bros  &lt;#&gt;  religiously.
4086    PRIVATE! Your 2003 Account Statement for 07973...
Name: message, dtype: object

In [23]:
#Vectorize
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
X_train_vectorized=vectorizer.fit_transform(X_train)

In [25]:
X_train_dense = X_train_vectorized.toarray()
print(X_train_dense)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [27]:
#preprocessing
X_train_vectorized

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58978 stored elements and shape (4457, 7735)>